version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam package --s3-bucket {BucketName} --template-file template.yaml --output-template-file deploy.yaml
artifacts:
  files:
    - deploy.yaml
