AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
  BlogPostTableName:
    Description: Blogpost table name
    Type: String
  ReadCapacityUnits:
    Description: Read capacity units
    Type: Number
  WriteCapacityUnits:
    Description: Write capacity units
    Type: Number
  PrimaryKeyName:
    Description: Primary Key Name
    Type: String
  PrimaryKeyType:
    Description: Primary Key Type
    Type: String

Resources:
  BlogPostTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Join ["_", [!Ref Environment, !Ref BlogPostTableName]]
      PrimaryKey:
        Name: !Sub "${PrimaryKeyName}"
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
