AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
  BlogPostTableName:
    Description: Blogpost table name
    Type: String
  ReadCapacityUnits:
    Description: Read capacity units
    Type: Number
  WriteCapacityUnits:
    Description: Write capacity units
    Type: Number

Resources:
  BlogPostTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["_", [!Ref Environment, !Ref BlogPostTableName]]
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: title
          AttributeType: S

      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

  BlogPostTableGetItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for getItem on BlogPost table
      ManagedPolicyName:
        !Join ["_", [!Ref Environment, "BlogPostTableGetItem", "Policy"]]
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "dynamodb:GetItem"
            Resource: !GetAtt BlogPostTable.Arn

  BlogPostTablePutItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for PutItem on BlogPost table
      ManagedPolicyName:
        !Join ["_", [!Ref Environment, "BlogPostTablePutItem", "Policy"]]
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "dynamodb:PutItem"
            Resource: !GetAtt BlogPostTable.Arn

  BlogPostTableDeleteItemPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for DeleteItem on BlogPost table
      ManagedPolicyName:
        !Join ["_", [!Ref Environment, "BlogPostTableDeleteItem", "Policy"]]
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "dynamodb:DeleteItem"
            Resource: !GetAtt BlogPostTable.Arn
